/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfmbomba.java
 *
 * Created on 20/11/2011, 10:46:44
 */
package forms;

import arquivos.ArquivoInBomba;
import arquivos.ArquivoInTanque;
import arquivos.ArquivoOutBomba;
import classes.bomba;
import classes.tanque;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tassio
 */
public class jfmbomba extends javax.swing.JFrame {

    private ArquivoInBomba arqinbmb = new ArquivoInBomba();
    private ArquivoInTanque arq = new ArquivoInTanque();
    private tanque tq = null;
    private bomba bb = null;
    int linha;
    int linhatanque;
    private ArquivoOutBomba arqoutbmb = new ArquivoOutBomba();

    /** Creates new form jfmbomba */
    public jfmbomba() {

        try {
            initComponents();
            arqoutbmb.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(jfmbomba.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(jfmbomba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbomba = new javax.swing.JTextField();
        jbtaddbomba = new javax.swing.JButton();
        txttanquevinc = new javax.swing.JTextField();
        txtcombbomba = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelabombacad = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbombavinc = new javax.swing.JTextField();
        txttanquevinc2 = new javax.swing.JTextField();
        txtcombvinc = new javax.swing.JTextField();
        jbtalterarbomba = new javax.swing.JButton();
        jbtexcluirbomba = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabelalistabomba = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabelatanque = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bomba");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                pegatanques(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(570, 433));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero de Identificação:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 17, -1, -1));

        jLabel2.setText("Tanque vinculada:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 50, -1, -1));

        jLabel3.setText("Combustivel");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 83, -1, -1));

        txtbomba.setEnabled(false);
        jPanel1.add(txtbomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 12, 69, -1));

        jbtaddbomba.setText("Adicionar bomba");
        jbtaddbomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddbombaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtaddbomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, -1));

        txttanquevinc.setEnabled(false);
        jPanel1.add(txttanquevinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 45, 114, -1));

        txtcombbomba.setEnabled(false);
        jPanel1.add(txtcombbomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 78, 146, -1));

        jtabelabombacad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanque", "Capacidade", "Combustivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelabombacad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelabombacadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelabombacad);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 111, 420, 210));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Bomba:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jLabel5.setText("Tanque:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel6.setText("Combustivel:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 20, 80, 20));

        txtbombavinc.setEnabled(false);
        jPanel2.add(txtbombavinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, -1));

        txttanquevinc2.setEnabled(false);
        txttanquevinc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanquevinc2ActionPerformed(evt);
            }
        });
        jPanel2.add(txttanquevinc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));

        txtcombvinc.setEnabled(false);
        jPanel2.add(txtcombvinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 120, -1));

        jbtalterarbomba.setText("Alterar");
        jbtalterarbomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtalterarbombaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtalterarbomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        jbtexcluirbomba.setText("Excluir");
        jbtexcluirbomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtexcluirbombaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtexcluirbomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 70, 180, -1));

        jtabelalistabomba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bomba", "Tanque", "Combustivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelalistabomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelalistabombaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabelalistabomba);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, 440, 86));

        jtabelatanque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanque", "Combustivel ", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelatanque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelatanqueMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtabelatanque);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 440, 100));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 10, 10, 50));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 50));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 10));

        jTabbedPane1.addTab("Controle", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 380));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-499)/2, (screenSize.height-438)/2, 499, 438);
    }// </editor-fold>//GEN-END:initComponents

    private void jtabelabombacadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelabombacadMouseClicked

        linha = jtabelabombacad.getSelectedRow();

        txttanquevinc.setText(jtabelabombacad.getValueAt(linha, 0).toString());
        txtcombbomba.setText(jtabelabombacad.getValueAt(linha, 2).toString());

    }//GEN-LAST:event_jtabelabombacadMouseClicked

    private void jbtaddbombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddbombaActionPerformed


        bb = new bomba(txtbomba.getText(),
                (txttanquevinc.getText()),
                (txtcombbomba.getText()));
        try {
            arqoutbmb.Adicionar(bb);
        } catch (IOException ex) {
            Logger.getLogger(jframetanque.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Bomba Inserido com sucesso!");

        txtbomba.setText(null);
        txttanquevinc.setText(null);
        txtcombbomba.setText(null);

        int cont = 1;

        List<bomba> listabomba = new ArrayList<bomba>();

        listabomba = arqinbmb.getTodasBomba();
        DefaultTableModel modelobomba = (DefaultTableModel) jtabelalistabomba.getModel();

        for (int i = jtabelalistabomba.getRowCount() - 1; i >= 0; --i) {
            modelobomba.removeRow(i);
        }

        for (int i = 0; i < listabomba.size(); i++) {
            modelobomba.addRow(listabomba.get(i).getbomba());
            cont++;
        }

        txtbomba.setText(String.valueOf(cont));



    }//GEN-LAST:event_jbtaddbombaActionPerformed

    private void pegatanques(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_pegatanques

        List<tanque> lista = new ArrayList<tanque>();

        lista = arq.getTodosTanque();

        DefaultTableModel modelo = (DefaultTableModel) jtabelatanque.getModel();

        for (int i = jtabelatanque.getRowCount() - 1; i >= 0; --i) {
            modelo.removeRow(i);
        }

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(lista.get(i).gettanque());
        }

        DefaultTableModel modelo2 = (DefaultTableModel) jtabelabombacad.getModel();

        for (int i = jtabelabombacad.getRowCount() - 1; i >= 0; --i) {
            modelo2.removeRow(i);
        }

        for (int i = 0; i < lista.size(); i++) {
            modelo2.addRow(lista.get(i).gettanque());
        }

        int cont = 1;

        List<bomba> listabomba = new ArrayList<bomba>();

        listabomba = arqinbmb.getTodasBomba();
        DefaultTableModel modelobomba = (DefaultTableModel) jtabelalistabomba.getModel();

        for (int i = jtabelalistabomba.getRowCount() - 1; i >= 0; --i) {
            modelobomba.removeRow(i);
        }

        for (int i = 0; i < listabomba.size(); i++) {
            modelobomba.addRow(listabomba.get(i).getbomba());
            cont++;
        }

        txtbomba.setText(String.valueOf(cont));

    }//GEN-LAST:event_pegatanques

    private void jbtalterarbombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtalterarbombaActionPerformed

        ArrayList<bomba> listab = new ArrayList<bomba>();
        listab = (ArrayList<bomba>) arqinbmb.getTodasBomba();


        String numerobomba = txtbombavinc.getText();
        String tanquevinculada = txttanquevinc2.getText();
        String combustiveltanque = txtcombvinc.getText();


        listab.get(linha).setNumero_bomba(numerobomba);
        listab.get(linha).setTanque_vinculado(tanquevinculada);
        listab.get(linha).setCombustivel_bomba(combustiveltanque);



        try {
            arqoutbmb.recadastrar_todos(listab);
        } catch (IOException ex) {
            Logger.getLogger(jfmbomba.class.getName()).log(Level.SEVERE, null, ex);
        }



        JOptionPane.showMessageDialog(null, "Aluguel Alterado com Sucesso!");


        txtbombavinc.setText(null);
        txttanquevinc2.setText(null);
        txtcombvinc.setText(null);

        DefaultTableModel modelo = (DefaultTableModel) jtabelalistabomba.getModel();

        if (jtabelalistabomba.getRowCount() > 0) {
            for (int i = jtabelalistabomba.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<bomba> listab2 = new ArrayList<bomba>();
        listab2 = arqinbmb.getTodasBomba();

        for (int i = 0; i < listab2.size(); i++) {
            modelo.addRow(listab2.get(i).getbomba());
        }

        int cont = 1;

        List<bomba> listabomba = new ArrayList<bomba>();

        listabomba = arqinbmb.getTodasBomba();
        DefaultTableModel modelobomba = (DefaultTableModel) jtabelalistabomba.getModel();

        for (int i = jtabelalistabomba.getRowCount() - 1; i >= 0; --i) {
            modelobomba.removeRow(i);
        }

        for (int i = 0; i < listabomba.size(); i++) {
            modelobomba.addRow(listabomba.get(i).getbomba());
            cont++;
        }

        txtbomba.setText(String.valueOf(cont));


    }//GEN-LAST:event_jbtalterarbombaActionPerformed

    private void jbtexcluirbombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtexcluirbombaActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jtabelalistabomba.getModel();
        List<bomba> list = new ArrayList<bomba>();
        ArrayList<bomba> nova_list = new ArrayList<bomba>();
        linha = jtabelalistabomba.getSelectedRow();
        Object nome = modelo.getValueAt(linha, 0);
        list = arqinbmb.getTodasBomba();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getNumero_bomba().equals(txtbombavinc.getText()))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqoutbmb.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(jfmbomba.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtbombavinc.setText(null);
        txttanquevinc2.setText(null);
        txtcombvinc.setText(null);
        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Bomba apagada com sucesso");

        int cont = 1;

        List<bomba> listabomba = new ArrayList<bomba>();

        listabomba = arqinbmb.getTodasBomba();
        DefaultTableModel modelobomba = (DefaultTableModel) jtabelalistabomba.getModel();

        for (int i = jtabelalistabomba.getRowCount() - 1; i >= 0; --i) {
            modelobomba.removeRow(i);
        }

        for (int i = 0; i < listabomba.size(); i++) {
            modelobomba.addRow(listabomba.get(i).getbomba());
            cont++;
        }

        txtbomba.setText(String.valueOf(cont));


    }//GEN-LAST:event_jbtexcluirbombaActionPerformed
    private void jtabelalistabombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelalistabombaMouseClicked

        linha = jtabelalistabomba.getSelectedRow();

        txtbombavinc.setText(jtabelalistabomba.getValueAt(linha, 0).toString());
        txttanquevinc2.setText(jtabelalistabomba.getValueAt(linha, 1).toString());
        txtcombvinc.setText(jtabelalistabomba.getValueAt(linha, 2).toString());

    }//GEN-LAST:event_jtabelalistabombaMouseClicked

    private void jtabelatanqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelatanqueMouseClicked

        linhatanque = jtabelatanque.getSelectedRow();
        txttanquevinc2.setText(jtabelatanque.getValueAt(linhatanque, 0).toString());
        txtcombvinc.setText(jtabelatanque.getValueAt(linhatanque, 2).toString());

    }//GEN-LAST:event_jtabelatanqueMouseClicked

private void txttanquevinc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanquevinc2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txttanquevinc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmbomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmbomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmbomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmbomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jfmbomba().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtaddbomba;
    private javax.swing.JButton jbtalterarbomba;
    private javax.swing.JButton jbtexcluirbomba;
    private javax.swing.JTable jtabelabombacad;
    private javax.swing.JTable jtabelalistabomba;
    private javax.swing.JTable jtabelatanque;
    private javax.swing.JTextField txtbomba;
    private javax.swing.JTextField txtbombavinc;
    private javax.swing.JTextField txtcombbomba;
    private javax.swing.JTextField txtcombvinc;
    private javax.swing.JTextField txttanquevinc;
    private javax.swing.JTextField txttanquevinc2;
    // End of variables declaration//GEN-END:variables
}
