/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jframetanque.java
 *
 * Created on 15/11/2011, 19:01:15
 */
package forms;

import arquivos.ArquivoOutTanque;
import arquivos.ArquivoInTanque;
import classes.tanque;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tassio
 */
public class jframetanque extends javax.swing.JFrame {

    private ArquivoInTanque arq = new ArquivoInTanque();
    private tanque tq = null;
    int linha;
    private ArquivoOutTanque arqout = new ArquivoOutTanque();

    /** Creates new form jframetanque */
    public jframetanque() {
        initComponents();
        try {
            initComponents();
            arqout.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(jframetanque.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(jframetanque.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumero_identtanque = new javax.swing.JTextField();
        txtcapacidade = new javax.swing.JTextField();
        jcbcombustivel = new javax.swing.JComboBox();
        jbotaoaddtanque = new javax.swing.JButton();
        jpanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelatanque = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtidentificador = new javax.swing.JTextField();
        txtcap = new javax.swing.JTextField();
        txtcomb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtalterar = new javax.swing.JButton();
        jbtexcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tanque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número de Identificação:");
        jpanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 55, -1, -1));

        jLabel2.setText("Capacidade (Litros):");
        jpanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 94, -1, -1));

        jLabel3.setText("Combustível armazenado:");
        jpanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 133, -1, -1));

        txtnumero_identtanque.setEnabled(false);
        jpanel1.add(txtnumero_identtanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 160, -1));
        jpanel1.add(txtcapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, -1));

        jcbcombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gasolina", "Etanol", "Diesel" }));
        jcbcombustivel.setSelectedIndex(-1);
        jpanel1.add(jcbcombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, -1));

        jbotaoaddtanque.setText("Adicionar");
        jbotaoaddtanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotaoaddtanqueActionPerformed(evt);
            }
        });
        jpanel1.add(jbotaoaddtanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 185, 120, -1));

        jTabbedPane1.addTab("Cadastro", jpanel1);

        jpanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabelatanque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Capaciade", "Combustível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelatanque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelatanqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelatanque);

        jpanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 480, 117));

        jLabel4.setText("Identificador:");
        jpanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, -1));

        txtidentificador.setEnabled(false);
        jpanel2.add(txtidentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, -1));
        jpanel2.add(txtcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, -1));

        txtcomb.setEnabled(false);
        jpanel2.add(txtcomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 140, -1));

        jLabel5.setText("Capacidade (Litros):");
        jpanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 140, -1));

        jLabel6.setText("Combustivel:");
        jpanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 120, -1));

        jbtalterar.setText("Alterar");
        jbtalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtalterarActionPerformed(evt);
            }
        });
        jpanel2.add(jbtalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        jbtexcluir.setText("Excluir");
        jbtexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtexcluirActionPerformed(evt);
            }
        });
        jpanel2.add(jbtexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 190, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, 60));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 20, 60));

        jTabbedPane1.addTab("Controle", jpanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 270));

        setSize(new java.awt.Dimension(529, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbotaoaddtanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotaoaddtanqueActionPerformed

        int cont = 1;
        tq = new tanque(txtnumero_identtanque.getText(),
                Integer.parseInt(txtcapacidade.getText()),
                jcbcombustivel.getSelectedItem().toString());
        try {
            arqout.Adicionar(tq);
        } catch (IOException ex) {
            Logger.getLogger(jframetanque.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Tanque Inserido com sucesso!");

        txtidentificador.setText(null);
        txtcap.setText(null);
        txtcomb.setText(null);

        DefaultTableModel modelo = (DefaultTableModel) jtabelatanque.getModel();

        if (jtabelatanque.getRowCount() > 0) {
            for (int i = jtabelatanque.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<tanque> listat2 = new ArrayList<tanque>();
        listat2 = arq.getTodosTanque();

        for (int i = 0; i < listat2.size(); i++) {
            modelo.addRow(listat2.get(i).gettanque());
            cont++;
        }

        txtnumero_identtanque.setText(String.valueOf(cont));
        txtcapacidade.setText(null);
        jcbcombustivel.setSelectedIndex(-1);


    }//GEN-LAST:event_jbotaoaddtanqueActionPerformed

    private void jtabelatanqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelatanqueMouseClicked

        linha = jtabelatanque.getSelectedRow();

        txtidentificador.setText(jtabelatanque.getValueAt(linha, 0).toString());
        txtcap.setText(jtabelatanque.getValueAt(linha, 1).toString());
        txtcomb.setText(jtabelatanque.getValueAt(linha, 2).toString());

    }//GEN-LAST:event_jtabelatanqueMouseClicked

    private void jbtalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtalterarActionPerformed


        ArrayList<tanque> listat = new ArrayList<tanque>();
        listat = (ArrayList<tanque>) arq.getTodosTanque();


        String identificador = txtidentificador.getText();
        int capacid = Integer.parseInt(txtcap.getText());
        String combustivel = txtcomb.getText();


        listat.get(linha).setNumero_identificacao(identificador);
        listat.get(linha).setCapacidade(capacid);
        listat.get(linha).setCombustivel(combustivel);
        try {
            arqout.recadastrar_todos(listat);
        } catch (IOException ex) {
            Logger.getLogger(jframetanque.class.getName()).log(Level.SEVERE, null, ex);
        }




        JOptionPane.showMessageDialog(null, "Capacidade alterado com Sucesso!");


        txtidentificador.setText(null);
        txtcap.setText(null);
        txtcomb.setText(null);

        DefaultTableModel modelo = (DefaultTableModel) jtabelatanque.getModel();

        if (jtabelatanque.getRowCount() > 0) {
            for (int i = jtabelatanque.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<tanque> listat2 = new ArrayList<tanque>();
        listat2 = arq.getTodosTanque();

        for (int i = 0; i < listat2.size(); i++) {
            modelo.addRow(listat2.get(i).gettanque());
        }


    }//GEN-LAST:event_jbtalterarActionPerformed

    private void jbtexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtexcluirActionPerformed
        int cont = 0;
        DefaultTableModel modelo = (DefaultTableModel) jtabelatanque.getModel();
        List<tanque> list = new ArrayList<tanque>();
        ArrayList<tanque> nova_list = new ArrayList<tanque>();
        linha = jtabelatanque.getSelectedRow();
        Object nome = modelo.getValueAt(linha, 0);
        list = arq.getTodosTanque();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getNumero_identificacao().equals(txtidentificador.getText()))) {
                nova_list.add(list.get(i));
            }
            cont++;
        }
        txtnumero_identtanque.setText(String.valueOf(cont));
        try {
            arqout.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(jfmbomba.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtcap.setText(null);
        txtcomb.setText(null);
        txtidentificador.setText(null);
        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Tanque apagada com sucesso");

    }//GEN-LAST:event_jbtexcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        List<tanque> lista = new ArrayList<tanque>();
        int cont = 1;

        lista = arq.getTodosTanque();
        DefaultTableModel modelo = (DefaultTableModel) jtabelatanque.getModel();

        for (int i = jtabelatanque.getRowCount() - 1; i >= 0; --i) {
            modelo.removeRow(i);
        }

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(lista.get(i).gettanque());
            cont++;
        }

        txtnumero_identtanque.setText(String.valueOf(cont));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframetanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframetanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframetanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframetanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jframetanque().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbotaoaddtanque;
    private javax.swing.JButton jbtalterar;
    private javax.swing.JButton jbtexcluir;
    private javax.swing.JComboBox jcbcombustivel;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JPanel jpanel2;
    private javax.swing.JTable jtabelatanque;
    private javax.swing.JTextField txtcap;
    private javax.swing.JTextField txtcapacidade;
    private javax.swing.JTextField txtcomb;
    private javax.swing.JTextField txtidentificador;
    private javax.swing.JTextField txtnumero_identtanque;
    // End of variables declaration//GEN-END:variables
}
