/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrmcombustivelsaida.java
 *
 * Created on 22/11/2011, 19:39:12
 */
package forms;

import arquivos.ArquivoInBomba;
import arquivos.ArquivoInCombustivel;
import arquivos.ArquivoInRelatorio;
import arquivos.ArquivoInTanque;
import arquivos.ArquivoOutCombustivel;
import arquivos.ArquivoOutRelatorio;
import classes.bomba;
import classes.combustivel;
import classes.relatorio;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tassio
 */
public class jfrmcombustivelsaida extends javax.swing.JFrame {

    private ArquivoInRelatorio arqinrelatorio = new ArquivoInRelatorio();
    private ArquivoInCombustivel arqincombustivel = new ArquivoInCombustivel();
    private ArquivoInBomba arqinbomba = new ArquivoInBomba();
    private relatorio cbr = null;
    int linha;
    int linhabomba;
    private ArquivoOutCombustivel arqoutcombustivel = new ArquivoOutCombustivel();
    private ArquivoOutRelatorio arqoutrelatorio = new ArquivoOutRelatorio();

    /** Creates new form jfrmCombustivel */
    public jfrmcombustivelsaida() {

        try {
            initComponents();
            arqoutcombustivel.abrir();
            arqoutrelatorio.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(jfrmcombustivelsaida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(jfrmcombustivelsaida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbcombustivel = new javax.swing.JComboBox();
        txtlitroestoque = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelacombustivel = new javax.swing.JTable();
        jbtentrada = new javax.swing.JButton();
        jbtsaida = new javax.swing.JButton();
        txtqtdes = new javax.swing.JTextField();
        txttanque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbomba = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabelabomba = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jbtrelatorio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabelarelatorio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combustivel");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Quantidade S/E:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 20, 90, -1));

        jLabel2.setText("Litros em estoque:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, -1));

        jLabel3.setText("Combustivel:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jcbcombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gasollina", "Etanol", "Diesel" }));
        jcbcombustivel.setSelectedIndex(-1);
        jcbcombustivel.setEnabled(false);
        jPanel1.add(jcbcombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        txtlitroestoque.setEnabled(false);
        jPanel1.add(txtlitroestoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 110, 20));

        jtabelacombustivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Combustivel", "Preço", "Estoque", "Tanque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelacombustivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelacombustivelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelacombustivel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 580, 84));

        jbtentrada.setText("Entrada de combustivel");
        jbtentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtentradaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, -1));

        jbtsaida.setText("Saida de Combustivel");
        jbtsaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsaidaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtsaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 180, -1));
        jPanel1.add(txtqtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 118, -1));

        txttanque.setEnabled(false);
        jPanel1.add(txttanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 60, 20));

        jLabel4.setText("Tanque:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 50, 40));

        jLabel5.setText("Preço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        txtpreco.setEnabled(false);
        jPanel1.add(txtpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 20));

        jLabel6.setText("Bomba:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, 20));

        txtbomba.setEnabled(false);
        jPanel1.add(txtbomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 70, -1));

        jtabelabomba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bomba", "Tanque", "Combustivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelabomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelabombaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtabelabomba);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 560, 140));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 40, 50));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, 50));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 40, 50));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 50));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 40, 50));

        jTabbedPane1.addTab("Controle", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtrelatorio.setText("Relatorio");
        jbtrelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtrelatorioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtrelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 150, -1));

        jtabelarelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Combustivel", "Preço", "Estoque", "Tanque", "Bomba"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtabelarelatorio);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 310));

        jTabbedPane1.addTab("Relatorio", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 420));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-699)/2, (screenSize.height-477)/2, 699, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtentradaActionPerformed

        ArrayList<combustivel> listac = new ArrayList<combustivel>();
        listac = (ArrayList<combustivel>) arqincombustivel.getTodoscombustiveis();


        String nome = jcbcombustivel.getSelectedItem().toString();
        String preco = txtpreco.getText();
        int litros = Integer.parseInt(txtlitroestoque.getText());
        int qtdes = Integer.parseInt(txtqtdes.getText());
        int es = qtdes + litros;
        String tanque = txttanque.getText();
        String bomba = txtbomba.getText();
        
        
        
        listac.get(linha).setNome(nome);
        listac.get(linha).setPreco(preco);
        listac.get(linha).setLitros(es);
        listac.get(linha).setTanque(tanque);

        cbr = new relatorio(nome, preco, es, tanque, null);
        try {
            arqoutrelatorio.Adicionar(cbr);
        } catch (IOException ex) {
            Logger.getLogger(jfrmcombustivelsaida.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            arqoutcombustivel.recadastrar_todos(listac);
        } catch (IOException ex) {
            Logger.getLogger(jfrmcombustivelsaida.class.getName()).log(Level.SEVERE, null, ex);
        }



        JOptionPane.showMessageDialog(null, "Quantidade de combustivel atualizado com Sucesso!");


        jcbcombustivel.setSelectedIndex(-1);
        txtlitroestoque.setText(null);
        txtpreco.setText(null);
        txtqtdes.setText(null);
        txttanque.setText(null);
        txtbomba.setText(null);

        DefaultTableModel modelo = (DefaultTableModel) jtabelacombustivel.getModel();

        if (jtabelacombustivel.getRowCount() > 0) {
            for (int i = jtabelacombustivel.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<combustivel> listab2 = new ArrayList<combustivel>();
        listab2 = arqincombustivel.getTodoscombustiveis();

        for (int i = 0; i < listab2.size(); i++) {
            modelo.addRow(listab2.get(i).getcombustivel());
        }
    }//GEN-LAST:event_jbtentradaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        List<bomba> listabomba = new ArrayList<bomba>();

        listabomba = arqinbomba.getTodasBomba();
        DefaultTableModel modelobomba = (DefaultTableModel) jtabelabomba.getModel();

        for (int i = jtabelabomba.getRowCount() - 1; i >= 0; --i) {
            modelobomba.removeRow(i);
        }

        for (int i = 0; i < listabomba.size(); i++) {
            modelobomba.addRow(listabomba.get(i).getbomba());
        }

        List<combustivel> lista = new ArrayList<combustivel>();

        lista = arqincombustivel.getTodoscombustiveis();
        DefaultTableModel modelo = (DefaultTableModel) jtabelacombustivel.getModel();

        for (int i = jtabelacombustivel.getRowCount() - 1; i >= 0; --i) {
            modelo.removeRow(i);
        }

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(lista.get(i).getcombustivel());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jtabelacombustivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelacombustivelMouseClicked



        linha = jtabelacombustivel.getSelectedRow();

        jcbcombustivel.setSelectedItem(jtabelacombustivel.getValueAt(linha, 0));
        txtpreco.setText(jtabelacombustivel.getValueAt(linha, 1).toString());
        txtlitroestoque.setText(jtabelacombustivel.getValueAt(linha, 2).toString());
        txttanque.setText(jtabelacombustivel.getValueAt(linha, 3).toString());


    }//GEN-LAST:event_jtabelacombustivelMouseClicked

    private void jbtsaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsaidaActionPerformed

        ArrayList<combustivel> listac = new ArrayList<combustivel>();
        listac = (ArrayList<combustivel>) arqincombustivel.getTodoscombustiveis();


        String nome = jcbcombustivel.getSelectedItem().toString();
        String preco = txtpreco.getText();
        int litros = Integer.parseInt(txtlitroestoque.getText());
        int qtdes = Integer.parseInt(txtqtdes.getText());
        String tanque = txttanque.getText();
        String bomba = txtbomba.getText();
        int bmb = -1;
        bmb = Integer.parseInt(bomba);
       if (bmb != -1){
        
        int es = litros - qtdes;
        if (qtdes > litros) {
            JOptionPane.showMessageDialog(null, "Quantidade Indisponivel em estoque");
        } else {
            

            listac.get(linha).setNome(nome);
            listac.get(linha).setPreco(preco);
            listac.get(linha).setLitros(es);
            listac.get(linha).setTanque(tanque);

            cbr = new relatorio(nome, preco, es, tanque, bomba);
            try {
                arqoutrelatorio.Adicionar(cbr);
            } catch (IOException ex) {
                Logger.getLogger(jfrmcombustivelsaida.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                arqoutcombustivel.recadastrar_todos(listac);
            } catch (IOException ex) {
                Logger.getLogger(jfrmcombustivelsaida.class.getName()).log(Level.SEVERE, null, ex);
            }



            JOptionPane.showMessageDialog(null, "Quantidade de combustivel atualizado com Sucesso!");


            jcbcombustivel.setSelectedIndex(-1);
            txtlitroestoque.setText(null);
            txtpreco.setText(null);
            txtqtdes.setText(null);
            txttanque.setText(null);
            txtbomba.setText(null);


            DefaultTableModel modelo = (DefaultTableModel) jtabelacombustivel.getModel();

            if (jtabelacombustivel.getRowCount() > 0) {
                for (int i = jtabelacombustivel.getRowCount() - 1; i >= 0; i--) {
                    modelo.removeRow(i);
                }
            }

            List<combustivel> listab2 = new ArrayList<combustivel>();
            listab2 = arqincombustivel.getTodoscombustiveis();

            for (int i = 0; i < listab2.size(); i++) {
                modelo.addRow(listab2.get(i).getcombustivel());
            }
        }
               }else{
           JOptionPane.showMessageDialog(null, "Não Foi informado a bomba de retirada do combustivel");
       }
    }//GEN-LAST:event_jbtsaidaActionPerformed

    private void jbtrelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtrelatorioActionPerformed


        DefaultTableModel modelo = (DefaultTableModel) jtabelarelatorio.getModel();

        if (jtabelarelatorio.getRowCount() > 0) {
            for (int i = jtabelarelatorio.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<relatorio> lista = new ArrayList<relatorio>();
        lista = arqinrelatorio.getTodasESComb();

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(lista.get(i).getrelatorio());
        }

    }//GEN-LAST:event_jbtrelatorioActionPerformed

    private void jtabelabombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelabombaMouseClicked
        
         linhabomba = jtabelabomba.getSelectedRow();
         txtbomba.setText(jtabelabomba.getValueAt(linhabomba, 0).toString());
         
    }//GEN-LAST:event_jtabelabombaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCombustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jfrmcombustivelsaida().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtentrada;
    private javax.swing.JButton jbtrelatorio;
    private javax.swing.JButton jbtsaida;
    private javax.swing.JComboBox jcbcombustivel;
    private javax.swing.JTable jtabelabomba;
    private javax.swing.JTable jtabelacombustivel;
    private javax.swing.JTable jtabelarelatorio;
    private javax.swing.JTextField txtbomba;
    private javax.swing.JTextField txtlitroestoque;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtqtdes;
    private javax.swing.JTextField txttanque;
    // End of variables declaration//GEN-END:variables
}
