/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 14/09/2011, 20:33:26
 */
package forms;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Tassio
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
        Dimension d = toolkit.getScreenSize();
        this.setSize(d.width, d.height);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuBar1 = new javax.swing.JMenuBar();
        jMcadastro = new javax.swing.JMenu();
        jmtanque = new javax.swing.JMenuItem();
        jmbomba = new javax.swing.JMenuItem();
        jMcombustivel = new javax.swing.JMenuItem();
        jmvolumetanque = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMconsulClientes = new javax.swing.JMenuItem();
        jMajuda = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMsobre = new javax.swing.JMenuItem();
        jMsair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setTitle("Principal");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jMenuItemSair, org.jdesktop.beansbinding.ELProperty.create("${selected}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        jMcadastro.setText("Cadastro");

        jmtanque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jmtanque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tanque (Cópia).jpg"))); // NOI18N
        jmtanque.setText("Tanque");
        jmtanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtanqueActionPerformed(evt);
            }
        });
        jMcadastro.add(jmtanque);

        jmbomba.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jmbomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/bomba.jpg"))); // NOI18N
        jmbomba.setText("Bomba");
        jmbomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbombaActionPerformed(evt);
            }
        });
        jMcadastro.add(jmbomba);

        jMcombustivel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMcombustivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gasolina (Cópia).jpg"))); // NOI18N
        jMcombustivel.setText("Combustivel");
        jMcombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcombustivelActionPerformed(evt);
            }
        });
        jMcadastro.add(jMcombustivel);

        jMenuBar1.add(jMcadastro);

        jmvolumetanque.setText("Controle");
        jmvolumetanque.add(jSeparator2);

        jMconsulClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMconsulClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/controle (Cópia).jpg"))); // NOI18N
        jMconsulClientes.setText("E/S de combustivel");
        jMconsulClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMconsulClientesActionPerformed(evt);
            }
        });
        jmvolumetanque.add(jMconsulClientes);

        jMenuBar1.add(jmvolumetanque);

        jMajuda.setText("Ajuda");
        jMajuda.add(jSeparator3);

        jMsobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        jMsobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sobre (Cópia).png"))); // NOI18N
        jMsobre.setText("Sobre");
        jMsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsobreActionPerformed(evt);
            }
        });
        jMajuda.add(jMsobre);

        jMenuBar1.add(jMajuda);

        jMsair.setText("Sair");
        jMsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsairActionPerformed(evt);
            }
        });

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair (Cópia).png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMsair.add(jMenuItemSair);

        jMenuBar1.add(jMsair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-648)/2, (screenSize.height-491)/2, 648, 491);
    }// </editor-fold>//GEN-END:initComponents

    private void jMsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsairActionPerformed

    }//GEN-LAST:event_jMsairActionPerformed

    private void jMsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsobreActionPerformed
        Locale locale = new Locale("pt", "BR");
        GregorianCalendar calendar = new GregorianCalendar();
        SimpleDateFormat formatador = new SimpleDateFormat("dd' de 'MMMMM' de 'yyyy' - 'HH':'mm' hrs'", locale);
        JOptionPane.showMessageDialog(null, "Autor: \n Tássio Ferenzini M. Sirqueira \n Data e Hora Atual:\n " + formatador.format(calendar.getTime()), "Sobre", WIDTH);
    }//GEN-LAST:event_jMsobreActionPerformed

    private void jmbombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbombaActionPerformed
        jfmbomba bomba = new jfmbomba();
        bomba.setVisible(true);
    }//GEN-LAST:event_jmbombaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        jfmsair sair = new jfmsair();
        sair.setVisible(true);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jmtanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtanqueActionPerformed
        jframetanque jft = new jframetanque();
        jft.setVisible(true);
    }//GEN-LAST:event_jmtanqueActionPerformed

    private void jMcombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcombustivelActionPerformed
       
         jfrmCombustivel jfc = new jfrmCombustivel();
        jfc.setVisible(true);
        
    }//GEN-LAST:event_jMcombustivelActionPerformed

    private void jMconsulClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMconsulClientesActionPerformed
       
         jfrmcombustivelsaida jfces = new jfrmcombustivelsaida();
        jfces.setVisible(true);
        
    }//GEN-LAST:event_jMconsulClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                Principal janela = new Principal();
                janela.setVisible(true);
                /*
                new Principal().setVisible(true);
                janela.setVisible(true);
                 * 
                 */
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMajuda;
    private javax.swing.JMenu jMcadastro;
    private javax.swing.JMenuItem jMcombustivel;
    private javax.swing.JMenuItem jMconsulClientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMsair;
    private javax.swing.JMenuItem jMsobre;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem jmbomba;
    private javax.swing.JMenuItem jmtanque;
    private javax.swing.JMenu jmvolumetanque;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
